# Generated by Django 4.1.7 on 2023-03-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='work',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
