# Generated by Django 4.1.7 on 2023-03-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_review_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='bishkek_number',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='ik_number',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='ja_number',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='osh_number',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
