# Generated by Django 4.1.7 on 2023-03-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settings_bishkek_number_settings_ik_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='exp',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='students',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
