# Generated by Django 4.1.7 on 2023-03-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_countries_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='date',
        ),
    ]
